spring:
  application:
    name: e-commerce
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
e-commerce:
    token:
      secret: ${JWT_SECRET:secret-key}
product:
    image:
      directory: C:/Users/letic/Projetos-Backend/e-commerce/images
      servlet:
        multipart:
          enabled: true
          max-file-size: 1GB
          max-request-size: 1GB